[package]
name = "vm-interp"
version = "0.1.0"
edition = "2024"

[dependencies]
bitvec = "1.0.1"
clap = { version = "4.5.55", features = ["derive"] }
libc = "0.2.186"
vm-core = { path = "../vm-core" }

[build-dependencies]
bindgen = "0.72.1"

[features]
default = []
verbose = []
runtime_checks = []
