[[case]]
name = "mandelbrot"
rapira_source = "benchmarks/sources/мандельброт.рап"
python_source = "benchmarks/sources/мандельброт.py"
rapira_stdin = "190\n"
python_stdin = "190\n"
output_sha256 = "93fb065e7e472121f01e73881a946acaef3b1205121f71f7ac8c6410fd7f3e6b"
tags = ["float", "loops"]

[[case]]
name = "fibonacci"
rapira_source = "benchmarks/sources/int_fib_mod.рап"
python_source = "benchmarks/sources/int_fib_mod.py"
output_sha256 = "443e206d0d30eae3c8bd5c472cd501978a74ddb9d674827d43aa51322aa930ee"
tags = ["integer", "loops"]

[[case]]
name = "binary-tree"
rapira_source = "benchmarks/sources/binary_tree.rap"
python_source = "benchmarks/sources/binary_tree.py"
rapira_stdin = "18\n"
python_args = ["18"]
output_sha256 = "35c1e2a47f64aedfc4f1bf009ed5df059ac9332dfb6372e87723313e5747a719"
tags = ["allocation", "recursion"]

[[case]]
name = "nbody"
rapira_source = "benchmarks/sources/nbody.рап"
python_source = "benchmarks/sources/nbody.py"
rapira_stdin = "400000\n"
python_stdin = "400000\n"
output_sha256 = "bb95e5b4a695aecad180818ca9cc67aa2ac84ed7d24e1e7d329c5369125f8e8c"
tags = ["float", "loops", "tuple"]

[[case]]
name = "fannkuch-redux"
rapira_source = "benchmarks/sources/fannkuch_redux.рап"
python_source = "benchmarks/sources/fannkuch_redux.py"
rapira_stdin = "10\n"
python_stdin = "10\n"
output_sha256 = "26f4debed9b9f8db7609e17f35756a3f72c1d85d40977a4377a1ef34ffc4d4c8"
tags = ["integer", "loops", "tuple", "branches"]

[[case]]
name = "reverse-complement"
rapira_source = "benchmarks/sources/reverse_complement.рап"
python_source = "benchmarks/sources/reverse_complement.py"
# Generated with: python3 benchmarks/sources/fasta.py 250000
# TODO: bump this number when we are not so...slow...
stdin_file = "benchmarks/inputs/reverse_complement.fasta"
output_sha256 = "8722f28c80fa027f2ca82557e4cb56d854f3d7e908be8d6aaa303423de2efc15"
tags = ["text", "allocation", "loops", "branches", "io"]
